### ISSUE TITLE
Get rid of autoload

### ISSUE THREAD

**Issue by epa** [leejo/CGI.pm#162]
Back in olden days autoload might have shaved a little off CGI.pm startup time, but CPUs are faster than they used to be (relative to disk I/O and all the other things which take time), and besides, any web application where performance is important doesn't start a new perl process (and load CGI.pm afresh) for each request.

I suggest simplifying the code by removing the autoload stuff and just having ordinary subroutines parsed at compile time.

**Comment by leejo** [comment]
DEV version 4.13_01 going out to CPAN with these changes.

**Comment by sjohnston** [comment]
There are quite a few tags missing in this release. I think "html_functions.t" is not really useful for testing backwards-compatibility since it only checks for methods that are defined in the code.

**Comment by sjohnston** [comment]
The "html_functions.t" test is still useful for explicitly testing the output generated by _tag_func so I left it alone and created a new test to check for undefined exported functions.

**Comment by leejo** [comment]
> There are quite a few tags missing in this release. I think "html_functions.t" is not really useful for testing backwards-compatibility since it only checks for methods that are defined in the code.

Yeah. This was more of a regression test, since i wrote it to pass pre-merge of the AUTOLOAD changes. Seems i missed a few of the weirder (probably mistakenly names) tags with different cases (Area, Tr, etc). Anyway, will get this fixed. Thanks!

**Comment by sjohnston** [comment]
Another issue to consider: looks like we'll loose the '-any' pragma. At the very least, POD will need to be updated.
Same goes for "Special forms for importing HTML-tag functions".

**Comment by leejo** [comment]
Good catch. The -any pragma looks like a bad/dangerous thing - i've checked a few code search engines and can't see anything using it (including on CPAN or github) so i'm going to remove it and include a warning if it is used.

**Comment by epa** [comment]
I do suggest a deprecation cycle will be needed for these things.  CGI.pm has a lot of quite ancient code using it, which won't show up on CPAN or in code search engines - perhaps more for CGI.pm than for any other module.  At the least, it needs to wait until after CGI.pm is unbundled from the perl core, since a new perl core release has fairly high backwards-compatibility requirement.

**Comment by leejo** [comment]
> At the least, it needs to wait until after CGI.pm is unbundled from the perl core, since a new perl core release has fairly high backwards-compatibility requirement.

v3.65 was the last version of CGI.pm to go out with the perl core so the backwards-compatibility requirement is no longer a hard one (although i am making efforts to retain this in the v4 releases).

You can't get a more recent version of CGI.pm unless you use CPAN, a vendor package, or install manually; if you're doing this then you *should* be testing any upgrade no matter how trivial (debian, et al, essentially maintain their own fork of perl modules so all bets are off if you're using a vendor-package). If an update breaks your code then you either fix your code or stick with the last version that didn't break your code.

For edge case stuff like this i'm not so concerned with backwards-compatibility, and the cruft needs to go.

**Comment by epa** [comment]
Ah, so it has already been dropped from perl core for the purposes of future releases.  And if the new version has a bumped major number to 4, that should indicate some cruft-clearing has happened ;-p

**Comment by leejo** [comment]
> Ah, so it has already been dropped from perl core for the purposes of future releases. And if the new version has a bumped major number to 4, that should indicate some cruft-clearing has happened ;-p

Yep, and i'm trying to get the word out that changes are happening. Even so, there will always be users that will install CGI.pm (either directly or indirectly) and just expect it to work. No amount of noise or number of deprecation cycles is going to make them aware that their code might [soon] break, hence treading carefully with the v4 release. I'm really going to gut the module in the v5 releases, but that won't happen until next year at the earliest.

**Comment by sjohnston** [comment]
In testing this release against my codebase, I've noticed a change in output for the special-case tags, Tr, TR, Sub, Area, etc. In previous versions of CGI.pm, the tags are always lowercase in the output regardless of the method name. `<tr>` vs `<Tr>`

Since HTML is not case sensitive, it might not be a problem. I just wanted to at least mention it.

**Comment by leejo** [comment]
v4.14 on its way to CPAN.

**Comment by owendelong** [comment]
I realize I'm quite late to the party here, but due to stable running code, I haven't had to look at this until now. While I don't often use CGI::Pretty in production, I have found that it is _VERY_ useful for generating HTML code that can be read for debugging purposes.

There are, of course, alternatives (e.g. parsers that will make convert generated HTML code to pretty so it can be read), but adding yet another dependency in the debugging chain introduces yet additional places to hunt for bugs.

As such, if CGI::Pretty could be resurrected, that would be appreciated. If not, c'est la vie, but it's a painful parting.
