### ISSUE TITLE
 Use of uninitialized value $ENV{"HTTP_USER_AGENT"}

### ISSUE THREAD

**Issue by nigelhorne** [leejo/CGI.pm#168]
Sometimes I get this e-mail:

logs/concert-bands.co.uk/http/error.log:[Tue Feb 17 03:05:07 2015] [error] [client 96.255.71.203] [/cgi-bin/vacancy.pl - Tue Feb 17 03:05:07 2015] Use of uninitialized value $ENV{"HTTP_USER_AGENT"} in pattern match (m//) at /home/hornenj/perlmods/share/perl/5.14.2/CGI/Carp.pm line 582.

And no, it isn't when I'm running my CGI script from the command line.  Perhaps some bots don't set HTTP_USER_AGENT, and CGI::Alert can't handle these cases?

**Comment by leejo** [comment]
This is just a warning so not much to worry about. I'll have a look at adding a test and fixing it though.

BTW, your homepage is giving a 500 internal server error: http://www.nigelhorne.com/cgi-bin/index.fcgi

**Comment by nigelhorne** [comment]
On 2/27/15 2:35 PM, Lee J wrote:
>
> This is just a warning so not much to worry about. I'll have a look at 
> adding a test and fixing it though.
>

Are you sure?  When ever I get that message I don't receive the 
attachments and stack trace I would otherwise receive.
>
> BTW, your homepage is giving a 500 internal server error: 
> http://www.nigelhorne.com/cgi-bin/index.fcgi
>

Oops.  Should be ok now - well spotted!

-Nigel

**Comment by leejo** [comment]
> Are you sure?  When ever I get that message I don't receive the attachments and stack trace I would otherwise receive.

Hmm, are you using MSIE by any chance? Here's the chunk of code raising the warning:

```perl
579         print STDOUT "Status: 500\n";
580         print STDOUT "Content-type: text/html\n\n";
581         # MSIE won't display a custom 500 response unless it is >512 bytes!
582         if ($ENV{HTTP_USER_AGENT} =~ /MSIE/) {
583           $mess = "<!-- " . (' ' x 513) . " -->\n$mess";
584         }
585         print STDOUT $mess;
```

**Comment by nigelhorne** [comment]
On 02/28/2015 06:13 AM, Lee J wrote:
>
>     Are you sure? When ever I get that message I don't receive the
>     attachments and stack trace I would otherwise receive.
>
> Hmm, are you using MSIE by any chance? Here's the chunk of code 
> raising the warning:
>
> 579print  STDOUT  "Status: 500\n";
> 580print  STDOUT  "Content-type: text/html\n\n";
> 581# MSIE won't display a custom 500 response unless it is >512 bytes!
> 582if  ($ENV{HTTP_USER_AGENT} =~ /MSIE/) {
> 583$mess  ="\n$mess";
> 584         }
> 585print  STDOUT  $mess;

I've no Idea what client is being used because HTTP_USER_AGENT isn't set :-)

My best hunch is it's a bot of some time.

-Nigel
