### ISSUE TITLE
4.x bad self_url  when SCRIPT_NAME = PATH_INFO 

### ISSUE THREAD

**Issue by naox** [leejo/CGI.pm#176]
CGI-4.14 (probably 4.x) If env variables SCRIPT_NAME (for example /a.pl) and PATH_INFO (for example a.pl) are equal self_url returns url like this http://domain.org/a.pl/a.pl If SCRIPT_NAME and PATH_INFO are not equal then proper http://domain.org/a.pl is returned.
CGI.pm-3.65 (probably 3.x) - problem is not occuring

**Comment by leejo** [comment]
Bisected back to 44ab08c8397afd423c52da6c729d01818bf5d17e

**Comment by leejo** [comment]
@naox - i believe the above fix should handle this, can you test?

**Comment by naox** [comment]
yes, problem is not longer occuring on a HEAD version

**Comment by leejo** [comment]
> yes, problem is not longer occuring on a HEAD version

Thanks! This will go out in the next release.
