### ISSUE TITLE
regression: tmpFileName() now expects file-handle argument (upload), not filename (param)

### ISSUE THREAD

**Issue by smcv** [leejo/CGI.pm#178]
CGI.pm documents that this should work and return the filename in /tmp, if `$q` is a CGI object and `an_upload` is a file-upload field:

    $q->tmpFileName(scalar $q->param('an_upload'))

[ikiwiki](http://ikiwiki.info/) relies on this behaviour, and it worked in CGI.pm 3.x. However, in CGI.pm 4.09, that doesn't work. I've done some digging and found that the required parameter to tmpFileName seems to be the file-handle, not the filename:

    $q->tmpFileName(scalar $q->upload('an_upload'))

Please fix either the regression or the documentation.

I'm going to make ikiwiki try both possibilities and use whichever is defined and non-empty; please let me know which way is your preferred API for this, and I'll make it try that one first.

**Comment by leejo** [comment]
Could you try with the latest version of CGI.pm and see if the problem also exists there? I refactored the temp file handling a while back and it went through a few, er, iterations...

Envoyé par myMail pour iOS


dimanche, 7 juin 2015 09:34 -0400 de Simon McVittie  <notifications@github.com>:

**Comment by smcv** [comment]
The 4.09 behaviour of needing the filehandle instead of the filename is still there in 4.15 (more precisely Debian's 4.15-1, but Debian doesn't apply any patches to this particular package). There don't seem to have been any relevant changes since then.

**Comment by smcv** [comment]
I've pushed a failing test (marked as TODO) to my clone of CGI.pm.

```
...
ok 17 - check it acts like a handle
ok 18 - can call seek() on handle result
Use of uninitialized value in concatenation (.) or string at /usr/share/perl5/CGI.pm line 3554.
not ok 19 - tmpFileName(param(field)) works # TODO https://github.com/leejo/CGI.pm/issues/178
#   Failed (TODO) test 'tmpFileName(param(field)) works'
#   at t/upload.t line 141.
Use of uninitialized value in concatenation (.) or string at /usr/share/perl5/CGI.pm line 3554.
Use of uninitialized value in numeric eq (==) at t/upload.t line 143.
not ok 20 - tmpFileName result has desired size # TODO https://github.com/leejo/CGI.pm/issues/178
#   Failed (TODO) test 'tmpFileName result has desired size'
#   at t/upload.t line 143.
ok 21 - tmpFileName(upload(field)) works
ok 22 - tmpFileName result has desired size
...
```

**Comment by leejo** [comment]
Fancy having a crack at a fix? I'm currently abroad sans laptop and will be for two more weeks. I'll have a look at this, and any pull request, when I'm back.

Merci !
Lee.

Envoyé par myMail pour iOS


lundi, 8 juin 2015 17:07 -0400 de Simon McVittie  <notifications@github.com>:
>I've pushed a failing test (marked as TODO) to my clone of CGI.pm.
>...
ok 17 - check it acts like a handle
ok 18 - can call seek() on handle result
Use of uninitialized value in concatenation (.) or string at /usr/share/perl5/CGI.pm line 3554.
not ok 19 - tmpFileName(param(field)) works # TODO https://github.com/leejo/CGI.pm/issues/178
#   Failed (TODO) test 'tmpFileName(param(field)) works'
#   at t/upload.t line 141.
Use of uninitialized value in concatenation (.) or string at /usr/share/perl5/CGI.pm line 3554.
Use of uninitialized value in numeric eq (==) at t/upload.t line 143.
not ok 20 - tmpFileName result has desired size # TODO https://github.com/leejo/CGI.pm/issues/178
#   Failed (TODO) test 'tmpFileName result has desired size'
#   at t/upload.t line 143.
ok 21 - tmpFileName(upload(field)) works
ok 22 - tmpFileName result has desired size
...

**Comment by smcv** [comment]
I'll try to fix it if you can tell me what I'm aiming for. What do you consider the "most correct" behaviour to be? Please pick one:

* only `$q->tmpFileName($q->param('an_upload'))`, i.e. filename-based, works (compatible with 3.x, consistent with documentation, breaks code that relies on 4.09)
* only `$q->tmpFileName($q->upload('an_upload'))` i.e. filehandle-based, works (compatible with 4.09, incompatible with 3.x, documentation would need fixing)
* both work, filehandle (`$q->upload`) is preferred
* both work, filename (`$q->param`) is preferred

I'm guessing you want the third or fourth, to minimize regressions; perhaps the third is best, to make sure it works even if the uploader gave the same filename for two different file-upload fields?

**Comment by leejo** [comment]
Yep, 3rd seems a good choice.

Lee.

Envoyé par myMail pour iOS


mardi, 9 juin 2015 10:27 -0300 de Simon McVittie  <notifications@github.com>:

**Comment by smcv** [comment]
It's more subtle than I'd realised:

* `$q->tmpFileName($q->param('an_upload'))` works
* `$q->tmpFileName("".$q->param('an_upload'))` doesn't work

(because the former argument is a File::Temp reference and the latter is just a string).

Opening a PR with a fix.
