### ISSUE TITLE
Odd number of elements in hash assignment

### ISSUE THREAD

**Issue by ab2300** [leejo/CGI.pm#181]
The following warning is reported in perl version 5.20 when the readonly and the disabled controls are used in form fields:

Odd number of elements in hash assignment at /usr/lib/perl5/site_perl/5.20.1/CGI/Util.pm line 117.

**Comment by leejo** [comment]
This is an HTML generation function, which are no longer being maintained except for critical issues. If you can supply a PR with tests i'm happy to take a look, but otherwise this won't be looked at. Thanks!
