### ISSUE TITLE
mod_perl issue when running under Taint mode

### ISSUE THREAD

**Issue by ANSI-C** [leejo/CGI.pm#182]
Hello, I am getting this error message on apache logs:

(in cleanup) Insecure dependency in eval while running with -T switch at /usr/local/share/perl5/CGI.pm line 933.

where in specified line I find:
```perl
eval "package $pack; $code";
```
please advise if this is actually a bug or if there is a way to overcome it by specific configuration.

**Comment by leejo** [comment]
This was part of the _compile and AUTOLOAD logic and was removed in recent versions. I suggest you upgrade to the latest version of CGI.pm to get rid of this.

**Comment by ANSI-C** [comment]
Thank you very much for prompt reply!

Il 09/07/2015 08.00, Lee J ha scritto:
