### ISSUE TITLE
Problem dealing with URI encoded GET requests

### ISSUE THREAD

**Issue by edgreenberg** [leejo/CGI.pm#183]
When the web server sends a redirect on a GET request with parameters, it will (may?) URI encode the parameters.  I saw this using semicolon parameter separators, where  A=B;C=D became A=B%3bC=D.

In CGI.pm's parse_params() subroutine, we sparate parameters with 
       my(@pairs) = split(/[&;]/,$tosplit);
but that fails when the paraeters are URI encoded.

Either we need to URI-decode the param string first, or we need to enhance the regex to split on %3b (and maybe %38 for ampersand as well.) 

I'm not sure what the preferred way to fix this is, or I would submit a patch. 

If you tell me what that preferred fix is, I'll be happy to construct and test a patch. 

Thanks, 
Ed Greenberg

**Comment by leejo** [comment]
Can you describe what the desired parameters after parsing in this example should be? I may be misunderstanding the issue, but any request to the server should *not* be URL encoding the separators so the query string `A=B%3bC=D` should actually be parsed to the key `A` and value `B;C=D` - you want the value to contain a semicolon so you URI encoded that value to *prevent* if from being split into `A` is `B` and `C` is `D`. CGI.pm already decodes any URL encoding when parsing the query string.

You can URI encoded the keys and the values in the query string, but you should *not* be URL encoding the separators. The relevant section of the IETF RFC is [thus](https://tools.ietf.org/html/rfc3875#section-2.3), which states:

```
   To encode a character string, all reserved and forbidden characters
   are replaced by the corresponding "%" escape sequences.  The string
   can then be used in assembling a URI.  The reserved characters will
   vary from context to context, but will always be drawn from this set:

      reserved = ";" | "/" | "?" | ":" | "@" | "&" | "=" | "+" | "$" |
                 "," | "[" | "]"

   The last two characters were added by RFC 2732 [7].  In any
   particular context, a sub-set of these characters will be reserved;
   the other characters from this set MUST NOT be encoded when a string
   is URL-encoded in that context.
```

**Comment by edgreenberg** [comment]
On 07/30/2015 07:49 AM, Lee J wrote:
>
> Can you describe what the desired parameters after parsing in this 
> example should be? I may be misunderstanding the issue, but any 
> request to the server should /not/ be URL encoding the separators so 
> the query string |A=B%3bC=D| should actually be parsed to the key |A| 
> and value |B;C=D| - you want the value to contain a semicolon so you 
> URI encoded that value to /prevent/ if from being split into |A| is 
> |B| and |C| is |D|. CGI.pm already decodes any URL encoding when 
> parsing the query string.
>

The desired parameters:  A=B   and    C=D

I didn't encode this.  Apache did. On second thought, perhaps Plesk 
configured Apache to do so.  Hang on with this. It may be a plesk bug.


I'll get back to you.

Ed G

**Comment by leejo** [comment]
This is almost certainly a bug in your code or whatever you're using to URL encode - it should not be encoding the separators. I'm closing this as i don't believe there's anything wrong in CGI.pm here. Let me know if you find otherwise.
