### ISSUE TITLE
Problem retrieving parameter value using $value = $query->param('foo');

### ISSUE THREAD

**Issue by egvibar** [leejo/CGI.pm#184]
Hello, Lee. I can't seem to retrieve parameter values using  $query->param('foo'); I am wondering if you could please help me. I'd appreciate your help. Thanks. egv.

**Comment by leejo** [comment]
Can you show me the code you are using please?

**Comment by egvibar** [comment]
Thank you for responding, Lee. I used the following code:

use CGI;
my $query = CGI->new;
my $country = $query->param('country');

I was hoping to retrieve the parameter value that my HTML passed to the script. However, for some reason that is unknown to me,  $query->param('country'); can't seem to retrieve it. I tested a snippet of the old CGI script below and it worked. Of course, I trust CGI.pm more than snippet code below. I hope this helps. Thank you, Lee. egvibar.

# CGI PARSING
		# Read in text
		$ENV{'REQUEST_METHOD'} =~ tr/a-z/A-Z/;
		my $buffer;    
		if ($ENV{'REQUEST_METHOD'} eq "POST") {read(STDIN,$buffer,$ENV{'CONTENT_LENGTH'});}
		else {$buffer = $ENV{'QUERY_STRING'}};
        
		# Split information into key/value pairs
		my @split1; 
		my $arraySize; 
		@split1 = split(/&/, $buffer);
    
		my %FORM;
		my $split1;    
		my $key;
		my $value;
		foreach $split1 (@split1)
		{
		($key, $value) = split(/=/, $split1);
		$key =~ tr/+/ /;
		$key =~ s/%(..)/pack("C", hex($1))/eg;
		$value =~ tr/+/ /;
		$value =~ s/%(..)/pack("C", hex($1))/eg;
		$FORM{$key} = $value;
		}

		my $country = $FORM{'country'};

**Comment by leejo** [comment]
This:

```perl
#!perl

use strict;
use warnings;
use CGI;

my $query = CGI->new;
my $country = $query->param('country');
```

Should work fine, *assuming* your code is sat behind a webserver that can execute it and your webserver is passing the QUERY_STRING along to the cgi script for it to be parsed.

I'm not sure where you've got that CGI PARSING example from. It looks old and out of date and you shouldn't be manually messing around with things like the ENV variables and parsing query strings as that will happen within CGI.pm. It's why the module exists.

Anyway, if you're working on something new from scratch i suggest you ditch CGI.pm and use something more modern. See [CGI::Alternatives](https://metacpan.org/pod/CGI::Alternatives) for examples.

I'm closing this as github issues isn't really the place for help getting scripts working. This is for bug reports and pull requests. I would first suggest looking at the [examples](https://metacpan.org/source/LEEJO/CGI-4.21/examples) in the distribution, reading the [docs](https://metacpan.org/pod/distribution/CGI/lib/CGI.pod), and then asking at [stackoverflow](http://stackoverflow.com) or [perlmonks](http://www.perlmonks.org/)
