### ISSUE TITLE
CGI::Carp

### ISSUE THREAD

**Issue by epa** [leejo/CGI.pm#185]
Could CGI::Carp be kicked out into its own CPAN distribution?  Apart from a couple of example programs in doc/perl-CGI/examples, it doesn't have any dependencies to or from the rest of the CGI code.

**Comment by leejo** [comment]
It could yes, and given it's not used within CGI it probably makes sense to do this. Hmmm, and it appears i now have first-come on the module so there will be no permissions issues. I'll look at this sometime this/next week. I'd prefer to do it in a way that preserves the history.

**Comment by epa** [comment]
I guess you could add a CPAN distribution dependency so that CGI pulls in CGI::Carp.  Then somebody upgrading using the CPAN shell or whatever won't get a nasty surprise that Carp is gone from their system.  After some kind of deprecation period (CGI version 5.0?) that dependency could be dropped.

--
Ed Avis <eda@waniasset.com>

This email is intended only for the person to whom it is addressed and may contain confidential information. Any retransmission, copying, disclosure or other use of, this information by persons other than the intended recipient is prohibited. If you received this email in error, please contact the sender and delete the material. This email is for information only and is not intended as an offer or solicitation for the purchase or sale of any financial instrument. Wadhwani Asset Management LLP is a Limited Liability Partnership registered in England (OC303168) with registered office at 40 Berkeley Square, 3rd Floor, London, W1J 5AL. It is authorised and regulated by the Financial Conduct Authority.

**Comment by leejo** [comment]
Yes, that sounds sensible. I might do the same with CGI::Cookie (although this *is* required by CGI, it may be better in its own distribution also).

**Comment by leejo** [comment]
OK, going to leave this as is. I don't think the argument for extracting CGI::Carp to its own distribution is really compelling, and keeping the history intact is more important to me. Also CGI is a relatively small distribution now and this sort of change will probably annoy people, i don't think there's any benefit.

**Comment by epa** [comment]
Thanks for considering this request.  I will file any bugs against CGI::Carp as part of the main CGI distribution.
