### ISSUE TITLE
CGI::Alternatives dep

### ISSUE THREAD

**Issue by epa** [leejo/CGI.pm#186]
Since the documentation for CGI mentions CGI::Alternatives, it would be a good idea to add a package dependency on that so that the alternatives documentation is installed.  (Either that, or link to it as a URI rather than with L<> links to 'manual pages'.)

**Comment by leejo** [comment]
Another good idea. Feel free to make a PR, otherwise i'll get around to looking at this soon enough.

**Comment by leejo** [comment]
You know, i'm having second thoughts on this - my experience with vendor package managers and the like is that they will pull out any dependencies that aren't actually used by a distribution. So i think it would be better to have a link rather than pulling it in as a dep.

**Comment by epa** [comment]
No prob, a hyperlink works.  CGI::Alternatives is more discursive rather than technical documentation anyway, so it doesn't really need to be installed as a manual page.

**Comment by leejo** [comment]
I'm happy with what we've got here - the README.md links to the metacpan dist, whereas the POD has the L<> tags that will play well with CPAN/metacpan and the man pages.
