### ISSUE TITLE
investigate use of HTML::Tiny for HTML generation functions

### ISSUE THREAD

**Issue by leejo** [leejo/CGI.pm#189]
See: https://metacpan.org/pod/HTML::Tiny

**Comment by sjohnston** [comment]
I've considered this in the past. The problem is that the way they treat list of arguments vs. an array ref is backwards. Also CGI joins with ' ' where HTML::Tiny joins with ''. So, at the very least, you'd need a compatibility wrapper.

**Comment by leejo** [comment]
Ah, i'd hoped it would be a little more trivial. In that case, nuts to it! Thanks for the info.

**Comment by epa** [comment]
See also https://rt.cpan.org/Ticket/Display.html?id=110879

**Comment by archenemies** [comment]
Please keep the existing CGI interface for HTML generation functions. I have plenty of scripts which generate static HTML using ``print start_html(...);``, then stuff like ``print p(...)``, then ``print end_html(...)``. It would be a huge headache to have to wrap them in a single ``$h->html(...)`` call. All the indentation would change, I would have to change the way that loops operate and generally rewrite and retest everything I have. Also, thank you leejo for taking on maintenance of this module. (let me know if you wanted me to post this somewhere else)

**Comment by leejo** [comment]
@archenemies - the HTML generation functions will remain in CGI.pm in their current form so you don't need to worry. Rather than remove them i, and others, are taking the approach of strongly discouraging their use.

Removing or refactoring them is too much effort for too little gain; the consequence of potentially breaking thousands of user's scripts, or passing on a heavy maintenance penalty, simply isn't worth it.
