### ISSUE TITLE
No Space Between Commonly Used Attributes Using checkbox with -no_xhtml Pragma

### ISSUE THREAD

**Issue by ViktorNacht** [leejo/CGI.pm#190]
Creating a checkbox with the -no_xhtml pragma set and commonly used attributes results in a missing space between some attribute value and the next attribute, as show below between the value and id attributes.

I hope you'll consider fixing this, or accepting a Pull Request to do so since it causes so much legacy code to now fail validation.

    use CGI qw(-no_xhtml :all);

    say checkbox({id=>'foo', name=>'foo', value=>'bar', label=>'Foo Bar'});
    # <input type="checkbox" name="foo" value="bar"id="foo" >Foo Bar

**Comment by leejo** [comment]
Hi! Sorry, all the HTML generation functionality of CGI.pm is considered deprecated so i won't be looking at this myself. If you can provide a fully tested PR i will consider it.
