### ISSUE TITLE
DELETE request, handle request data

### ISSUE THREAD

**Issue by benrubson** [leejo/CGI.pm#199]
Hello,

For POST and PUT request, `param('keywords')` returns the request body / data.
However, it stays empty for DELETE requests.
Could we think about assigning `param('keywords')` for DELETE requests too ?

Thank you very much :+1: 

Ben

**Comment by benrubson** [comment]
I encounter this issue using jQuery ajax() method with DELETE requests.

From the jQuery manual (http://api.jquery.com/jquery.ajax/) :
`Data (...) is appended to the url for GET-requests.`
So for other requests (and so for DELETE requests), data remains in the request's body.

Should be then perfect to have CGI.pm `param('keywords')` set for DELETE requests too.

Thank you :+1:

**Comment by leejo** [comment]
Is this the same as #64 ?

**Comment by benrubson** [comment]
Not really no, #64 handles URI parameters (`$ENV{'QUERY_STRING'}`).
However I think it would be useful/interesting to also grab data from request's body, as done for POST and PUT requests.
However I'm not sure both can be done at the same time in a safe way.

**Comment by leejo** [comment]
OK, there was a previous request to do this, my response can be seen here: https://github.com/leejo/CGI.pm/issues/87#issuecomment-50152638

If you can have a look at this then i'm happy to accept a PR for it, but i won't be handling it myself (i'm still of the opinion that a DELETE method having body content is a poorly designed API, but i understand that is subjective).

**Comment by leejo** [comment]
@benrubson - any thoughts on this? As i state in the linked issues, it's possible but i couldn't see a way to support it without breaking backwards compatibility. As before, i'm more than open to a PR if it can be done in a clean way and *not* break backwards compatibility.

**Comment by benrubson** [comment]
Lee, here is the PR : #200.
Of course tested without issue.

Thank you !

**Comment by leejo** [comment]
Excellent, will close this and comment on the PR.
