### ISSUE TITLE
Documentation on redirect

### ISSUE THREAD

**Issue by andrewsolomon** [leejo/CGI.pm#206]
In CGI.pod we have

> You should always use full URLs (including the http: or ftp: part) in
>  redirection requests. Relative URLs will not work correctly.

However with the example here [https://tools.ietf.org/html/rfc7231#section-7.1.2](https://tools.ietf.org/html/rfc7231#section-7.1.2) and the documentation here [https://tools.ietf.org/html/rfc3986#section-5](https://tools.ietf.org/html/rfc3986#section-5) my understanding is that we don't need a full URL.

Is this an error, or have I misunderstood?

**Comment by leejo** [comment]
You don't need the full URL. Perhaps i should clarify the docs (it's entirely possible the docs predate any clarifications in the RFC). Just to avoid any confusion, if you visit `http://foo.com/bar/baz` then the following `Location` header values will (*should* given this is down to the user agent to resolve) result in a redirect to:

Location value| Where the user agent should go
------------ | -------------
`/boz` |  `http://foo.com/boz`
`boz`| `http://foo.com/bar/boz`
`http://blah.com`|`http://blah.com`
