### ISSUE TITLE
When $foo = param('foo') is called with multiple values, document which value is returned

### ISSUE THREAD

**Issue by markstos** [leejo/CGI.pm#209]
This is regard to the docs, looking at this section:

https://github.com/leejo/CGI.pm/blob/master/README.md#fetching-the-value-or-values-of-a-single-named-parameter

Particularly this sentence: " Otherwise the method will return a single value."

Instead of "single value", I recommend clarifying either the *first* value or the *last* value passed.

Thanks for maintaining CGI.pm. 

At the very moment I'm trying get the Express Node.js framework to add something like the param(), multi_param() pair. Because it lacks them, apps are vulnerable to DoS or other problems if an array of values is passed when a single value was expected.

**Comment by leejo** [comment]
Hi Mark,

Good point. I'll check the tests tomorrow and clarify the docs.

Cheers,
Lee.

Lee A Johnson
https://leejo.github.io
