### ISSUE TITLE
url_param and the command line

### ISSUE THREAD

**Issue by epa** [leejo/CGI.pm#210]
CGI supports running a script on the command line passing a string of key=value arguments.  This is broadly equivalent to fetching the CGI page with those parameters in the URI.

The `url_param()` function only looks at parameters passed in the URI, the intention being to ignore those passed the body of a POST request.  But `url_param()` also excludes those passed on the command line:

````
% perl -MCGI -E '$x = CGI::param("x") // "undef"; say $x' x=5
5
% perl -MCGI -E '$x = CGI::url_param("x") // "undef"; say $x' x=5
undef
````

I think it would be more useful for `url_param()` to include things passed on the command line, if the script is being run from the command line (in other words if `request_method()` returns undef).  Since this will not affect use of CGI on a real website I think it is not a big compatibility break, but it will make debugging and testing somewhat easier.

If you agree with the principle, I can write a patch and send a pull request.

**Comment by leejo** [comment]
Is it any kind of compatibility break? Patch is welcome as always, but only if the test coverage is included - and that would mean adding any missing coverage to prevent any regressions. Cheers!

**Comment by epa** [comment]
I made a pull request https://github.com/epa/CGI.pm/pull/2 but it is against my own repository instead of yours; at the moment I can't work out how to make Github transfer it across.

**Comment by leejo** [comment]
Try closing your PR and reopening it.

**Comment by epa** [comment]
I think I was trying to be too clever making my changes on a branch in my fork.  I've merged them into master and then the change is just between your master and my master.

https://github.com/leejo/CGI.pm/pull/211

**Comment by epa** [comment]
Hi, do you remember why this feature was reverted?  Is there a way I can rework the patch to get it included?  Being able to pass parameters on the command line is a very handy feature for writing tests, and it's awkward that they don't get picked up by `url_param()`.

**Comment by leejo** [comment]
@epa - https://github.com/leejo/CGI.pm/issues/212#issuecomment-253520225

**Comment by epa** [comment]
Thanks, I'd forgotten about that link.  You might still want to apply the documentation improvements in the early part of the patch series.
