### ISSUE TITLE
Packaging base cgi / Code issue ( Trusty => Xenial )

### ISSUE THREAD

**Issue by dohnuts** [leejo/CGI.pm#213]
My FCGI service is broken when updating from two LTS ubuntu release,
$q->header is not supporting custom http field anymore:

It stop when i call , print $q->header(-status => 500, dbg => "ERROR32")
which is what the test should reply,

Last executed line is :

CGI::unescapeHTML(/usr/share/perl5/CGI.pm:2220):
2220:       require HTML::Entities;

which seem to be present here:
/usr/lib/x86_64-linux-gnu/perl5/5.22/HTML/Entities.pm

This did not exist in the previous version.

Moreover, when dropping priviledge i lost the ref and i had to launch the program
with -I /usr/lib/x86_64-linux-gnu/perl5/5.22

require in the middle of the code looks bad, 
moreover it is no more possible to have custom fields
in reply, which was somewhat convenient.

Best.

**Comment by leejo** [comment]
This isn't an issue with the CGI.pm distribution, it's an issue with a) using the system provided perl and, b) the vendors not including HTML::Entities as part of the CGI.pm package, which is explicitly listed as being a requirement in the Makefile.PL: https://github.com/leejo/CGI.pm/blob/master/Makefile.PL#L27

You need to raise an issue with Debian/Ubuntu.

**Comment by dohnuts** [comment]
Dude the file is present,
the Entities is setup,
but because the require is in the middle of the code it raises pathfind issue,
which i can solve BUT

the main problem is the drop of the custom field support

The call
$q->header(-status => 500, -dbg => "ERROR32")
kill the process !!!

I try to contact pkg-perl-maintainers@lists.alioth.debian.org but it looks like a robot list.

I really do thing the require should be a use at the top.

Especially if it well specified as required like you did show.

**Comment by leejo** [comment]
So the question is why isn't the path to HTML::Entities in your `@INC`?

Yes, custom field support was removed in v4.21: https://github.com/leejo/CGI.pm/blob/master/Changes#L127

If you need this then you will have to use an earlier version.

**Comment by dohnuts** [comment]
So far i am just guessing it s my setuid that mess up with the includes.
I do not understand exactly why the require failed, and it did not happen when running perl -d
only perl without -d ,
i solved it with a -I when running in non debug mode.

Thank you for pointing the changes i ll know where to look for them now.
