### ISSUE TITLE
Unavoidable deprecated message

### ISSUE THREAD

**Issue by CarlEklof** [leejo/CGI.pm#221]
Using CGI.pm will create a message to STDERR:
CGI will be removed from the Perl core distribution in the next major release. **Please install it from CPAN**. It is being used at $path/$whateverfile, line XXX.

Even the CPAN version does this. So following those instructions does not address the issue. The CPAN version should not send the deprecation message.

**Comment by leejo** [comment]
Can you give me your output from `perl -V` and `pmpath CGI` please. The deprecation warning should *only* occur if the CPAN module is installed in one of the *core* library directories. If the module is located in one of the site directories, as it should be if installed from CPAN, then no warning should be issued.

**Comment by duke-m** [comment]
or from the ports-tree on a real OS ;) (BSD)

**Comment by leejo** [comment]
Closing due to lack of response.

**Comment by leejo** [comment]
Reopening, I'll remove the deprecation check now since the version on CPAN is above the last version that was bundled with core.

**Comment by leejo** [comment]
v4.49 on its way to CPAN
