### ISSUE TITLE
CGI::Cookie max-age=0 implementation

### ISSUE THREAD

**Issue by gmillerd** [leejo/CGI.pm#226]
I realize that the documentation reads that max-age is experimental, but I thought I would write this up as it's a change I have made use of.

The max-age cookie token is allowed to have a value of "0". When passed to CGI::Cookie, this is ignored (or when passed as +0s, 0s, +0Y, +0.0s, etc

This assists in expiring cookies that are for the browser 'session' (non-persistent), but the browser window closes (such as Chrome and it's Resume where you left off, or "keep stuff running when browser quits", etc)

https://www.w3.org/Protocols/rfc2109/rfc2109

A short hack on a cookie that has no -expire such as this shows the behavior.

        ` CGI::Cookie->new({   }) . "; max-age=0" `

Thanks, I have found yours and Lincoln's work amazing.

**Comment by leejo** [comment]
Hi, thanks! I'll look at updating the docs to include this (I'll also double check the RFCs to see if the behaviour is correct).
