### ISSUE TITLE
ExtUtils::MakeMaker version issues

### ISSUE THREAD

**Issue by remorse** [leejo/CGI.pm#228]
Hi! If you try to upgrade the version of CGI installed with Perl 5.16 (and probably others) from a fresh install of 5.16, it will fail. In particular, the version of ExtUtils::MakeMaker that comes with 5.16 doesn't support the 'TEST_REQUIRES' keyword. You should probably include a minimum version of ExtUtils::MakeMaker in the dependencies, so that it will be properly installed...

**Comment by leejo** [comment]
Thanks! Looking at this now...

**Comment by ap** [comment]
Btw I can’t find any other mention of it anywhere in the dist… except in `configure_requires`. Why did you add that there?

**Comment by ap** [comment]
Btw I can’t find any other mention of File::Spec::Functions anywhere in the dist… except in `configure_requires`. Why did you add that there?
