### ISSUE TITLE
ExtUtils::MakeMaker version issues, take 2

### ISSUE THREAD

**Issue by ap** [leejo/CGI.pm#229]
Hi,

you dealt with #228 by using `CONIFGURE_REQUIRES`. That only shifts the problem, though. CGI.pm’s minimum Perl requirement is 5.8.1 and CoreList says an EUMM with `CONFIGURE_REQUIRES` support didn’t ship in core until 5.10.1. Even so, it wasn’t until 5.14 that the CPAN.pm in core actually had reliable, functional `configure_requires` support. So you’ve effectively only pushed the problem back by one Perl version.

Even so, upgrading the user’s EUMM just in order to install CGI.pm is a painful experience. A recent EUMM also has recent deps, and they have recent deps in turn. Forcing a new toolchain first makes installation take minutes instead of seconds.

Since you are using EUMM already, the better approach than using `configure_requires` is to write your `Makefile.PL` (roughly) [in the style of how e.g. Dist::Zilla::Plugin::MakeMaker would generate it](https://metacpan.org/source/RJBS/Dist-Zilla-6.012/lib/Dist/Zilla/Plugin/MakeMaker.pm#L95-116): replace the single big `WriteMakefile` call with a `my %WriteMakefileArgs =` assignment, then follow it with a bunch of `unless eval { ExtUtils::MakeMaker->VERSION(...) }` bits that `delete` bits from the hash and, where relevant at install time, reassign them as the vaguely equivalent older feature, and only afterwards do `WriteMakefile( %WriteMakefileArgs );`.

In your case you would delete `TEST_REQUIRES` and merge it into `BUILD_REQUIRES` if EUMM was too old for `TEST_REQUIRES`; merge `BUILD_REQUIRES` into `PREREQ_PM` if EUMM was too old for that; also, delete `META_MERGE` if EUMM was too old for that (since it’s only relevant to someone using EUMM to create a release tarball, i.e. basically just you – it doesn’t matter at install time).

That way, your `Makefile.PL` just works with however old a version of EUMM the user has.

I am willing to prepare a PR for this.

**Comment by leejo** [comment]
Resolved by #230
