### ISSUE TITLE
CGI.pm Link Broken

### ISSUE THREAD

**Issue by lsherwood** [leejo/CGI.pm#231]
The second of the two links in the section "CGI.pm HAS BEEN REMOVED FROM THE PERL CORE" is broken. 

Here is the URL:

http://www.nntp.perl.org/group/perl.perl5.porters/2013/05/msg202130.html

It gives this error:

Error
load() - DBD::mysql::st execute failed: MySQL server has gone away at /usr/local/share/perl5/site_perl/Rose/DB/Object.pm line 422. at /cnntp/combust/lib/Combust/RoseDB/Manager.pm line 8.

**Comment by leejo** [comment]
That's an issue with the remote server, not the link itself. It now appears to be working. Closing.
