### ISSUE TITLE
The licensing is not clear

### ISSUE THREAD

**Issue by autarch** [leejo/CGI.pm#232]
The license text in the POD is this:

> The CGI.pm distribution is copyright 1995-2007, Lincoln D. Stein. It is distributed under GPL and the Artistic License 2.0. It is currently maintained by Lee Johnson (LEEJO) with help from many contributors.

What version of the GPL? And is something like "GPL 2.0 or later" or is it "GPL 2.0 only"?

Also, I think that you probably mean "or" where you have "and". As it stands, this statement says that both the "GPL" and the Artistic 2.0 license apply, not that we can choose one.

**Comment by leejo** [comment]
TBH I have absolutely no idea, this one needs to be clarified with Lincoln as to what the original license was and what it currently should be.

**Comment by leejo** [comment]
Looking at the commit logs this goes as far back 3feb00ff40413404072743f10d06864e47eda7a6

**Comment by leejo** [comment]
Prior to that it was "under the same terms as Perl itself", and prior to that it was author copyright by Lincoln: https://github.com/leejo/CGI.pm/commit/8e166003694202477201d70962ef7982f3234297#diff-ae07bd5e8a02c046df065292654b56f5L5989

**Comment by leejo** [comment]
AFAIA there was no version control pre CVS (1998) so that would require digging through backpan: https://metacpan.org/pod/release/LDS/CGI.pm-2.10/CGI.pm#AUTHOR-INFORMATION

**Comment by autarch** [comment]
I'm guessing the license text you found in the oldest git commit is probably the same as what it was before that. That said, I think all that's needed is a clarification of the current license.

If the goal is to make it like Perl itself _except_ with Artistic 2.0 then it should say this:

```
This program is free software; you can redistribute it and/or modify
it under the terms of either:

	a) the GNU General Public License as published by the Free
	Software Foundation; either version 1, or (at your option) any
	later version, or

	b) the Artistic License 2.0 as defined by The Perl Foundation.
```

And then you should include both the GPL 1.0 and Artistic license as separate files (typically GPL is `COPYING` and Artistic is `LICENSE`).

**But** that may not be what is wanted, since the Artistic License 2.0 itself says in its text that you can choose a different license:

```
	(i)  the Original License or

	(ii)  a license that permits the licensee to freely copy,
	modify and redistribute the Modified Version using the same
	licensing terms that apply to the copy that the licensee
	received, and requires that the Source form of the Modified
	Version, and of any works derived from it, be made freely
	available in that license fees are prohibited but Distributor
	Fees are allowed.
```

So what I've started doing for all my Perl modules is to _only_ license them under Artistic 2.0, because that gives people same license freedom as the Perl 5 "GPL 1.0+ or Artistic 1.0" did, plus allows for other copyleft licenses besides the GPL.

**Comment by leejo** [comment]
@autarch - please see above commit, can you check that you're happy that removes any ambiguity? If so, I'll upload to CPAN.

**Comment by autarch** [comment]
This is good, but it'd be even better to also include a copy of the Artistic 2.0 in a `LICENSE` file.

**Comment by leejo** [comment]
OK, that's done and on its way to CPAN

**Comment by Grinnz** [comment]
LICENSE in Makefile.PL is still set to perl_5 and needs to be changed to artistic_2.

**Comment by leejo** [comment]
I was bound to miss something... v4.42 on its way to CPAN
