### ISSUE TITLE
start_form isn't mentioned in the man page

### ISSUE THREAD

**Issue by bkerin** [leejo/CGI.pm#236]
It does show up in

https://metacpan.org/pod/CGI::Alternatives

I don't know if this is deliberate gutting of the docs, but if so that makes me rather sad.  There's still a zillion people out there who just want to use CGI like they did, in ways for which it works totally fine and is still highly useful.  "hey just go learn mojolicious real quick" is not a very nice thing to say to them

**Comment by leejo** [comment]
Hi @bkerin - The docs have not been gutted, just reorganised to discourage the use of the HTML generation functions. The CGI.pm perldoc (man page) has the rationale here: https://metacpan.org/pod/distribution/CGI/lib/CGI.pod#HTML-Generation-functions-should-no-longer-be-used # and that links to all the original HTML functions documentation, namely here: https://metacpan.org/pod/distribution/CGI/lib/CGI/HTML/Functions.pod # in the case of `start_form`, here: https://metacpan.org/pod/distribution/CGI/lib/CGI/HTML/Functions.pod#Starting-and-ending-a-form

I'm closing this, as it appears there's nothing to do here.

**Comment by bkerin** [comment]
Ok thanks, I missed that.  I still don't see the point in organizing docs
st the good old funcs people vaguely remember are now hard to find though.
Discourage is fine, put "THESE FUNCTIONS ARE STUPID ONLY AN IDIOT WOULD USE
THEM" above if you want, but stick their names on page somewhere so they
can be found.

I'm trying to script quick db search helper for St Louis Approves, and for
me at least CGI is still significantly easier than e.g. Mojo (though I'm
looking into that for a larger project).  Respect your own software CGI is
still useful, separation of concerns and other political correctness be
damned.
