### ISSUE TITLE
$q->url(-rewrite=>0) doesn't return rewritten URI

### ISSUE THREAD

**Issue by travellingkiwi** [leejo/CGI.pm#242]
When using CGI via FCGI and calling from Apache 2.4 (RHEL-7) using ProxyPassMatch to rewrite the URI, the rewritten URI is not available at the CGI. Only the original URI is returned

Calling with
ProxyPassMatch "/api2/(.*)" "fcgi://some-server:8000/api/$1"

Accessing '$q->url(-rewrite=>1)' returns the original URL. As expected. However calling

'$q->url(-rewrite=>0)'

also returns the original URI.

**Comment by leejo** [comment]
As discussed over email:

```
Dumping the environment shows that the translated URI isn’t present anywhere…

Maybe mod_proxy_fcgi just doesn’t support rewrites…
```

So ... not sure what to do here

**Comment by travellingkiwi** [comment]
I've been doing some more looking into this. I think this is an issue upstream in the Apache itself. 

It appears that you can either proxy to fcgi, OR rewrite the URI. You can't do both at the same time, even though Apache shows in the logs rewrite trace output that it is doing it.

I've found that if I do the re-write on the URI only and then do a ProxyPassMatch i.e.

```
RewriteRule "/api2/(.*)" "/api/$1" [PT]
ProxyPassMatch "/api/" "fcgi://some-server:8000/"
```

then it works.
