### ISSUE TITLE
Copying max-age from a cookie

### ISSUE THREAD

**Issue by jjkola** [leejo/CGI.pm#248]
I copied cookie to another cookie with CGI::Cookie->new and it worked otherwise but there was a problem with max-age. The value copied is relative value but the interface is expecting either formatted string or absolute time. I had to circumvent the Cookie api and copy the value directly to member attribute to correctly copy the value. It would be nice if there was a way to do this through the api.

**Comment by leejo** [comment]
@jjkola - can you explain a bit more? My understanding here is that CGI::Cookie's constructor is not compatible with its own internal representation of the data. That maybe makes sense if we consider encapsulation but it would be nice if its constructor could infer that an attribute is valid from the point of view of the internal representation?

**Comment by leejo** [comment]
Closing due to lack of response
