### ISSUE TITLE
Getting error Odd number of elements in hash assignment at .../CGI/Util.pm line 112 in apache log file

### ISSUE THREAD

**Issue by jjkeijser** [leejo/CGI.pm#249]
I know this has been reported before, but I am seeing this error as well; it happens on a site running Twiki 6.1.0 which uses CGI::Util 4.13, but the code did not change WRT master. 
What I found with some debugging is that the headers sent for a Twiki page contain the following parameters:

```
[Tue May 18 23:16:52.298876 2021] [cgi:error] [pid 19013] [client xx] AH01215: param array has odd number of elements
[Tue May 18 23:16:52.299019 2021] [cgi:error] [pid 19013] [client xx] AH01215: param(0) = (-type)
[Tue May 18 23:16:52.299095 2021] [cgi:error] [pid 19013] [client xx] AH01215: param(1) = (image/jpeg),
[Tue May 18 23:16:52.299207 2021] [cgi:error] [pid 19013] [client xx] AH01215: param(2) = (Content-Disposition="inline;filename=default-user-profile.jpg")
[Tue May 18 23:16:52.299558 2021] [cgi:error] [pid 19013] [client xx] AH01215: [Tue May 18 23:16:52 2021] viewfile: Odd number of elements in hash assignment at /var/www/twiki-6.1.0/lib/CGI/Util.pm line 127.
```

and the question is how this array should be transformed into a hash. Other details: Perl 5.16.3

The above result was achieved by adding a blob
```
    if ($#param % 2 == 0) {
        print STDERR "param array has odd number of elements\n";
        my $ii = 0;
        foreach (@param) {
            print STDERR "param($ii) = ($_)\n";
            $ii++;
        }
    }   
```
to Util.pm

**Comment by leejo** [comment]
Hi! Can you test this with a more up to date version (current is 4.52).

**Comment by jjkeijser** [comment]
I just grabbed the 4.53 tarball , built it and replaced the files in the TWiki 6.1 directory with the new version. No luck, I am afraid, I now see
```
[Thu Jun  3 09:07:55 2021] view: CGI -any pragma has been REMOVED. You should audit your code for any use of none supported / incorrectly spelled tags and remove them at /var/www/twiki-6.1.0/lib/CGI.pm line 943., 

param array has odd number of elements,
param(0) = (-type), 
param(1) = (image/png), 
param(2) = (Content-Disposition="inline;filename=logo2.png"), 
[Thu Jun  3 09:07:56 2021] viewfile: Odd number of elements in hash assignment at /var/www/twiki-6.1.0/lib/CGI/Util.pm line 127.,

param array has odd number of elements, referer:
param(0) = (-type),
param(1) = (image/jpeg),
param(2) = (Content-Disposition="inline;filename=headerart.jpg"),
[Thu Jun  3 09:07:56 2021] viewfile: Odd number of elements in hash assignment at /var/www/twiki-6.1.0/lib/CGI/Util.pm line 127., 
```

**Comment by leejo** [comment]
Can you provide some context on how you're calling this? I need to be able to reduce down to a test case.

**Comment by jjkeijser** [comment]
Err, I installed and configured twiki 6.1.0, then went to the main landing page with a web browser and *boom*. 
The landing itself shows
```
<td valign="middle">
  <span id="twikiLogo" class="twikiImage">
    <a href="https://wiki.nikhef.nl/detector/Main/WebHome">
    <img src="/detector/pub/Main/TWikiPreferences/logo2.png" border="0" alt="Home - this site is powered by TWiki(R)" style="border:none;" />
    </a>
  </span>
</td>
```
but somehow that got mapped to `(Content-Disposition="inline;filename=logo2.png")`  - I have no clue which piece of code did that.

**Comment by leejo** [comment]
Honestly I suspect this is a bug in twiki calling something in CGI with a mixture of arguments that means when we map it to a hash it can't do it correctly (hence the warning). It looks like it's been called something like:

```perl
$cgi->foo(
    -type => "image/png",
    'Content-Disposition="inline;filename=logo2.png"'
);
```

Which is clearly going to be problematic. It *could* be a bug in CGI, but as I say without a test case/example code I'm not sure there's much I can do here.

**Comment by jjkeijser** [comment]
FWIW: this is Twiki 6.1.0 Response.pm calling  CGI::Util rearrange using
```
    my ( $type, $status, $cookie, $charset, $expires, $attachment, @other ) = 
      rearrange(
        [
            [ 'TYPE',   'CONTENT_TYPE', 'CONTENT-TYPE' ], 'STATUS',
            [ 'COOKIE', 'COOKIES' ],    'CHARSET',
            'EXPIRES', 'ATTACHMENT',
        ],  
        @p
      );

```

with @p containing the same lines I posted earlier

**Comment by jjkeijser** [comment]
further debugging:  Response.pm is called by TWiki View.pm:
```
618     my $type = TWiki::suffixToMimeType( $fileName );
619     $fileName = qq("$fileName") if ( $fileName !~ /^[-.\w]+$/ ); # Item7263
620     my $dispo = 'inline;filename='.$fileName;
621 
622     $session->{response}->header(-type => $type, qq(Content-Disposition="$dispo") );
```

is TWiki viewfile is constructing this header  with "-type ", "image/png", "Content-Disposition="inline;filename=logo2.png" which then gets pass to TWiki Response.pm then down to CGI::Util rearrange and we hit the warning.

**Comment by leejo** [comment]
Yep! That looks wrong to me, i think it should be:

```perl
$session->{response}->header(
    -type => $type,
    '-Content-Disposition' => $dispo,
);
```

**Comment by jjkeijser** [comment]
it then barfs somewhere else, causing apache httpd to write:
```
Response header name 'Inline;Filename' contains invalid characters, aborting request
```

I now realize what happens:
- the web page contains a ref to `<img src="/detector/pub/Main/TWikiPreferences/logo2.png">`
- the (default?) way to install a Twiki is to use a `<ScriptAlias>` so that everything starting with `/detector/pub/`  is handled by the Twiki viewfile script. 
- This script decides to write out a "Content-Disposition=inline;file=.../logo2png"  header and does so in a way that CGI::Util does not grok.

Perhaps the easiest workaround for me is to **stop** using `<ScriptAlias>` for content that can be served directly by httpd, such as .jpg, .png etc.

**Comment by leejo** [comment]
I guess 🤷‍♀️

Are we happy that appears to be an twiki bug and not a CGI.pm one?

**Comment by jjkeijser** [comment]
I'd say that is fine for now - although I am not sure what the proper fix would be for them. 
I've added a few `<AliasMatch>` statements to my apache config and now the warnings are gone - so I'm not going to care :smile:
