### ISSUE TITLE
_decode_utf8() method allows invalid UTF-8 sequences.

### ISSUE THREAD

**Issue by cmanley** [leejo/CGI.pm#257]
I noticed that the _decode_utf8() method decodes to Perl's lax utf8 encoding, which is not good if the data is being passed on into a database or some other medium which only tolerates valid UTF-8 sequences.
Shouldn't this line:
`return Encode::decode(utf8 => $val);`
be rewritten as:
`return Encode::decode('UTF-8', $val);`
See https://metacpan.org/dist/CGI/source/lib/CGI.pm#L463

This is what the Encode documentation mentions for decode_ut8:
https://perldoc.perl.org/Encode#decode_utf8
_`$string = decode_utf8($octets [, CHECK]);`
**WARNING: [This function accepts invalid UTF-8!](https://perldoc.perl.org/Encode#UTF-8-vs.-utf8-vs.-UTF8) Do not use it for data exchange.** Unless you want Perl's older "lax" mode, prefer `$string = decode("UTF-8", $octets [, CHECK])`_

**Comment by leejo** [comment]
Probably it should - but I don't see how we fix this without potentially breaking/corrupting the existing user-base's data, or introducing a new failure more, as I'm sure they will have put their own fixes in place.

If we do fix it then it will require the default to remain and a configuration variable to enable the fix. Happy to accept a PR to sort this (comprehensive test coverage being required).

**Comment by leejo** [comment]
@cmanley - thoughts? To me this is a "can'f fix", or "won't fix without comprehensive regression test coverage and being behind a flag to maintain backwards compatibility".

**Comment by cmanley** [comment]
@leejo For backwards compatibility, the only option I can think of is using a alternative flag/option than '-utf8', e.g. '-UTF8'.
But CGI has other legacy issues (such as not being able to subclass it properly) and we're phasing it out of our application anyway, so to me it's not really worth the time/effort to continue working on it.
