### ISSUE TITLE
IPv6 addresses not handled correctly

### ISSUE THREAD

**Issue by eserte** [leejo/CGI.pm#259]
If a CGI resource is accessed through a IPv6 address in bracket notation (e.g. `http://[::1]:5000`), then the `url()` function handles the host part wrongly by uri-escaping the brackets. Here's a demonstration of the problem:

```
#!/usr/bin/env perl

use strict;
use warnings;
use CGI;
use Test::More;

$ENV{HTTP_HOST} = '[::1]:5000';

my $cgi = CGI->new;
is $cgi->http('HTTP_HOST'), '[::1]:5000';
is $cgi->url, 'http://[::1]:5000';

done_testing;

__END__
```

Output is:
```
ok 1
not ok 2
#   Failed test at /tmp/cgi.pl line 12.
#          got: 'http://%5B::1%5D:5000'
#     expected: 'http://[::1]:5000'
1..2
# Looks like you failed 1 test of 2.
```

I checked if firefox or curl can handle such URLs, but it does not seem so:

```
$ curl 'http://%5B::1%5D:5000'
curl: (3) URL using bad/illegal format or missing URL
```

**Comment by zaucker** [comment]
@leejo This change broke one of our applications:
```perl
$url =~ s!/$!!;
```
This seems unrelated to the problem being fixed and leads to information loss (that the URL originally was pointing to a directory).
