### ISSUE TITLE
t/changes.t fails if Test::CPAN::Changes

### ISSUE THREAD

**Issue by eserte** [leejo/CGI.pm#260]
It seems that the test suite fails if Test::CPAN::Changes is installed:
```
#   Failed test 'Changes contains all valid release dates'
#   at t/changes.t line 12.
#   ERR: No date for version 3.65 (line 581)
# Looks like you failed 1 test of 4.
t/changes.t ................. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/4 subtests 
```
Sample report on CPAN Testers: http://www.cpantesters.org/cpan/report/93f4b338-76c0-11ee-a057-ddbcf3c92920

**Comment by leejo** [comment]
Thanks @eserte - looks like the rewrite of `Test::CPAN::Changes` is a bit more thorough so it finds issues in the older entries in the `Changes` file. Will sort this later.
