### ISSUE TITLE
tar: Ignoring malformed pax extended attribute

### ISSUE THREAD

**Issue by ryandesign** [leejo/CGI.pm#264]
Cannot extract CGI-4.63.tar.gz on older versions of macOS (e.g. 10.12).

```
tar: Ignoring malformed pax extended attribute
tar: Ignoring malformed pax extended attribute
tar: Ignoring malformed pax extended attribute
tar: Ignoring malformed pax extended attribute
tar: Error exit delayed from previous errors.
```

The MacPorts bug report about this is here: https://trac.macports.org/ticket/69077

**Comment by leejo** [comment]
@ryandesign - thanks. I'll have a look at this shortly.

I'll probably end up bumping the VERSION and packaging on a Linux host to see if that gets around this.

**Comment by ryandesign** [comment]
Or use `--no-xattrs` when creating the archive on a Mac. This is the default of GNU tar. The BSD tar manpage does not mention this option but I tried it and it does work (and does solve the problem).

**Comment by leejo** [comment]
@ryandesign - thanks, I think I'm going to `alias tar=tar --no-xattrs` as well 😄 

v4.64 on its way to CPAN.
