### ISSUE TITLE
review Wikipedia page

### ISSUE THREAD

**Issue by markstos** [leejo/CGI.pm#6]
There's a Wikipedia page about CGI.pm:

http://en.wikipedia.org/wiki/CGI.pm

It could use a review for potential updates. I see that the "current version" there is out of date, although that doesn't seem important to maintain there. Perhaps that part can just be removed.

**Comment by leejo** [comment]
The wikipedia page has been updated by myself (i've added the example to the branch i'm working on for #142). The wikibooks examples are reasonably sane so i've left as is.
